services:
  devcontainer:
    build:
      context: ../../containers/cuda/
      target: mpich
      args:
        MPICH_URL: "https://www.mpich.org/static/downloads/5.0.0/mpich-5.0.0.tar.gz"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
