services:
  devcontainer:
    build:
      context: ../../containers/cuda/
      target: workhorse
      args:
        OPENMPI_URL: "https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.8.tar.gz"
        MPI_VENDOR: openmpi
    volumes:
      - ../..:/workspaces:cached,Z
    command: sleep infinity
